run:
  timeout: 5m
  modules-download-mode: readonly
  # issues-exit-code: 1  # Завершает процесс с кодом ошибки, если есть проблемы

linters:
  disable-all: false
  enable:
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/LikeButterfly/tg-hotels-bot
